name: Build and Test

on: 
  workflow_dispatch:
  push:
    paths:
      - "src/Transmitly.ChannelProvider.Firebase/**"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: dotnet
        uses: actions/setup-dotnet@v3
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
      - name: Build netcore solution
        run: dotnet build Transmitly.ChannelProvider.Firebase.sln --configuration Debug -p:AssemblyVersion=${{ env.assemblySemVer }} -p:FileVersion=${{ env.assemblySemFileVer  }} -p:InformationalVersion=${{ env.informationalVersion }}
      #- name: Test
      #  run: dotnet test --no-build --no-restore --configuration Debug Transmitly.sln
      - name: Package
        run: dotnet pack --no-build --include-source /p:Version=${{ env.majorMinorPatch }}-alpha-${{env.buildMetaData}}.${{ env.shortSha }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: Publish Nuget
        run: dotnet nuget push src\Transmitly.ChannelProvider.Firebase\bin\Debug\Transmitly.ChannelProvider.Firebase*.nupkg -s "NugetTest" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      - name: Add github source
        run: dotnet nuget add source --username ${{ secrets.PUBLISH_GITHUB_USERNAME }} --password ${{ secrets.PUBLISH_GITHUB_PACKAGE_API_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/transmitly/index.json"
      - name: Publish (Github)
        run: dotnet nuget push src\Transmitly.ChannelProvider.Firebase\bin\Debug\Transmitly.ChannelProvider.Firebase*.nupkg --api-key ${{secrets.PUBLISH_GITHUB_PACKAGE_API_KEY}} --source "github"
        
