name: Release

on: 
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/.github/workflows/release-channel-provider.yml@main
    with: 
      channelProviderName: Transmitly.ChannelProvider.Firebase
    secrets: inherit
      
