name: Release

on: 
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  get_repo:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/.github/workflows/release-channel-provider.yml@main
    needs: get_repo
    with: 
      channelProviderName: Transmitly.ChannelProvider.Firebase
    secrets: inherit
      
